### PR TITLE
Update the `vulnscan.py` job to use a configuration file for Nessus API connectivity information

### LINKED ISSUE #4: Use a configuration file to store Nessus API credentials
# 🚀 Feature Proposal

Update the `VULNSCAN` job to ~~retrieve the Nessus password from the SSM Parameter Store using the EC2 instance's IAM profile~~ use a configuration file to supply the necessary credentials for accessing the Nessus httpd.

Note:
This will require changes to [cisagov/cyhy_amis](https://github.com/cisagov/cyhy_amis) to ~~set up the IAM profile and attach it to the instances~~ update the post-deployment Ansible role to create the configuration file that contains the necessary credentials.

## Motivation

Currently the Nessus password needed by the `VULNSCAN` job is hard-coded in the script. This is something that prevents the project from transitioning to the `cisagov` org as a public repository, and is a less than ideal solution. ~~AWS recommends using IAM profiles for applications running on EC2 instances that need to access external AWS resources in [their documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)~~ We can instead use a credentials file like we do for some of our other tools deployed in the same environment. This credential file will be created when the instance is deployed and will contain credentials that match what Nessus was configured to use. The script will access this file in an expected location to function.

## Example

Any time a `VULNSCAN` job is run this would be used instead of a hard-coded password.

## Pitch

This is a more secure way of handling this kind of access need. It will also remove one more roadblock from making this repository public.

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

Update the `vulnscan.py` job to retrieve Nessus API connection information from a configuration file in a known location. This closes #4.

## 💭 Motivation and context ##

Since this project no longer stores credentials in jobs we need to provide them externally. Fortunately for this project we did just that in https://github.com/cisagov/cyhy_amis/pull/542! Since the configuration file should exist in an expected location where this package is used by us we can update the `vulnscan.py` job in line with the updates to the `nessus_base.py` in the aforementioned pull request.

## 🧪 Testing ##

Sadly we have no automated tests. ~~TODO: Test this branch in my testing deployment to make sure it works as expected.~~ I have deployed this branch to my testing `database1` instance and verified that the `VULNSCAN` stage is able to run successfully.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).

### CODE REVIEW

**Comment by dav3r** [comment]
@mcdonnnj Can this PR also include a similar update to [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py), which can also double as a test for these changes?

**Comment by mcdonnnj** [comment]
> @mcdonnnj Can this PR also include a similar update to [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py), which can also double as a test for these changes?

@dav3r So looking at [`test_nessus.py`] it would require a complete rewrite as the implementation in [`vulnscan.py`] has diverged extensively from what [`test_nessus.py`] was originally designed to interface with for testing. I would prefer to update [`test_nessus.py`] along with [`vulnscan.py`] as part of #1 if you are amenable.

[`test_nessus.py`]: https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py
[`vulnscan.py`]: https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py

**Comment by dav3r** [comment]
> > @mcdonnnj Can this PR also include a similar update to [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py), which can also double as a test for these changes?
> 
> @dav3r So looking at [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) it would require a complete rewrite as the implementation in [`vulnscan.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py) has diverged extensively from what [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) was originally designed to interface with for testing. I would prefer to update [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) along with [`vulnscan.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py) as part of #1 if you are amenable.

Sure, no problem to take care of the `test_nessus.py` update as part of #1.  Please add some verbiage to #1 about that so that we don't forget.

**Comment by mcdonnnj** [comment]
> > > @mcdonnnj Can this PR also include a similar update to [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py), which can also double as a test for these changes?
> > 
> > 
> > @dav3r So looking at [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) it would require a complete rewrite as the implementation in [`vulnscan.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py) has diverged extensively from what [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) was originally designed to interface with for testing. I would prefer to update [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) along with [`vulnscan.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py) as part of #1 if you are amenable.
> 
> Sure, no problem to take care of the `test_nessus.py` update as part of #1. Please add some verbiage to #1 about that so that we don't forget.

I have a line in there about it but would you prefer something more prominent?

**Comment by dav3r** [comment]
> > > > @mcdonnnj Can this PR also include a similar update to [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py), which can also double as a test for these changes?
> > > 
> > > 
> > > @dav3r So looking at [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) it would require a complete rewrite as the implementation in [`vulnscan.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py) has diverged extensively from what [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) was originally designed to interface with for testing. I would prefer to update [`test_nessus.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py) along with [`vulnscan.py`](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py) as part of #1 if you are amenable.
> > 
> > 
> > Sure, no problem to take care of the `test_nessus.py` update as part of #1. Please add some verbiage to #1 about that so that we don't forget.
> 
> I have a line in there about it but would you prefer something more prominent?

Nope, I just missed that before when I scanned the issue - thanks! 👍

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
🎉 👍

**Pull request merged**
