### PR TITLE
Remove unused files and private repo blurb

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR removes various outdated and unused files.  It also replaces the "private repo" blurb from the README with some placeholder text since this repo is no longer private.

## 💭 Motivation and context ##

Doing some general cleanup of this repo now that it is public.

## 🧪 Testing ##

None.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Review by felddy — APPROVED** [review]
Spooktacular!  👻

**Review by mcdonnnj — COMMENTED** [review]
Do we need any of these job files?

- [nessus6_use_conf_file.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/nessus6_use_conf_file.py)
- [rand-sleep.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/rand-sleep.py) (optionally rename `rand-sleep-py3.py` to `rand-sleep.py` as part of that since runners are Python 3 only now)
- [restore-grub.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/restore-grub.sh)
- [test_nessus.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py)

It seems like we only need [basescan.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/basescan.sh), [netscan1.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/netscan1.sh), [netscan2.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/netscan2.sh), [portscan.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/portscan.sh), [vulnscan.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py), and I guess [rand-sleep-py3.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/rand-sleep-py3.py) for a null-op.

**Review by jsf9k — APPROVED** [review]
Removed code is bug-free code!

**Comment by dav3r** [comment]
> Do we need any of these job files?
> 
> * [nessus6_use_conf_file.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/nessus6_use_conf_file.py)
> * [rand-sleep.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/rand-sleep.py) (optionally rename `rand-sleep-py3.py` to `rand-sleep.py` as part of that since runners are Python 3 only now)
> * [restore-grub.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/restore-grub.sh)
> * [test_nessus.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/test_nessus.py)
> 
> It seems like we only need [basescan.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/basescan.sh), [netscan1.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/netscan1.sh), [netscan2.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/netscan2.sh), [portscan.sh](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/portscan.sh), [vulnscan.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/vulnscan.py), and I guess [rand-sleep-py3.py](https://github.com/cisagov/cyhy-commander/blob/develop/cyhy_commander/jobs/rand-sleep-py3.py) for a null-op.

Good call @mcdonnnj - I removed `nessus6_use_conf_file.py`, `rand-sleep.py`, and `restore-grub.sh` with https://github.com/cisagov/cyhy-commander/pull/8/commits/9414c17a61d9188b0b82e4d2211a8c0b5898c0e0 and I renamed `rand-sleep-py3.py` to `rand-sleep.py` (and updated the reference in `commander.py`) with https://github.com/cisagov/cyhy-commander/pull/8/commits/64dc011d75877284a68db633cda7d3b2b6f0afb4.

I'm going to keep `test_nessus.py` around for a bit longer.  I'm planning to update it (should only need minimal changes) and use it as a quick test when we modify `vulnscan.py` to use a config file for the Nessus API info (#4).

**Pull request merged**
